### ISSUE TITLE
abbreviate numbers like GitHub: 2,052 -> 2.1k

### ISSUE THREAD

**Issue by swharden** [swharden/repo-badge#1]
current behavior | GitHub
---|---
![image](https://user-images.githubusercontent.com/4165489/163097812-715236b5-1f7a-4ab3-917f-42fcc86fd899.png)|![image](https://user-images.githubusercontent.com/4165489/163097830-6938999f-829a-4b3c-b30d-3c059855d3e4.png)

**Comment by swharden** [comment]
Thanks for the suggestion @davefollett! This is the new default behavior, and adding a `data-exact` attribute to the `a` element will revert to showing the exact numerical value

```html
<a href="http://github.com/USER/REPO" id="github-stats-badge" data-exact>GitHub</a>
```

An "advanced configuration" section was added to the documentation page: https://swharden.github.io/repo-badge/

**Comment by davefollett** [comment]
Wonder what happens at a million stars?  If only GitHub itself was open sourced.

**Comment by davefollett** [comment]
Don't want to nit pick but, once the star value crosses over 100,000 the tenth place is rounded off it appears.  [FreeCodeCamp](https://github.com/freeCodeCamp/freeCodeCamp) has `343834` stars but displays `344k`.  Replacing https://github.com/swharden/repo-badge/blob/main/docs/badge.js#L78 with this:

```
let thousand = 0
if (value < 100000) {
  thousand = Math.round(value / 100) / 10;
} else {
  thousand = Math.round(value / 100 / 10);
}
```

**Comment by swharden** [comment]
Not a nitpick - thanks for the suggestion @davefollett!

I added this feature and set-up testing in GitHub Actions to ensure the output is what we expect 🚀 

![image](https://user-images.githubusercontent.com/4165489/163492641-7d07ee25-8446-438b-a8a8-aa2b1a774989.png)

The original behavior is hidden behind a `data-exact` flag you can add as an attribute

```
<a href="http://github.com/USER/REPO" id="github-stats-badge" data-exact>GitHub</a>
```

This advanced functionality is documented in a new section on the website https://swharden.github.io/repo-badge/
